ProjetoLojaDesktop/ProjetoLojaWeb/Controllers/OrdemServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoLojaData.Data;
using ProjetoLojaData.Entity;

namespace ProjetoLojaWeb.Controllers
{
    [Authorize]
    public class OrdemServicoController : Controller
    {
        private OrdemDeServicoData osData;
        private TransacaoData transacaoData;
        private ProdutoData produtoData;
        private UsuarioData usuarioData;

        public OrdemServicoController()
        {
            ProjetoLojaEntities db = new ProjetoLojaEntities();
            usuarioData = new UsuarioData(db);
            osData = new OrdemDeServicoData();
            transacaoData = new TransacaoData(db);
            produtoData = new ProdutoData();

        }

        public ActionResult Index()
        {
            Usuario u = usuarioData.obterUsuarioPorEmail(User.Identity.Name);
            int id = 3;//u.idPessoa;
            var lista = osData.listarOrdensDeServicoPorUsuarioLogado(id);
            return View(lista);
        }

        public JsonResult DetalhaOrdemServicoPorId(int id)
        {
            var detalhes = osData.obterOrdemDeServico(id);

            var produtos = from t in transacaoData.obterTransacao(id).TransacaoProduto
                       join p in produtoData.todosProdutos()
                           on t.idProduto equals p.idProduto
                       select new
                       {
                           descricao = p.descricao,
                           quantidade = t.qtdProduto,
                           valorUni = t.valorUnitario,
                           total = t.qtdProduto * t.valorUnitario
                       };

            var obj = new
            {
                id = detalhes.idTransacao,
                dataEntrada = detalhes.dataEntrada.ToShortDateString(),
                dataPrevistaEntrega = detalhes.dataPrevistaEntrega.ToShortDateString(),
                dataEntrega = (detalhes.dataEntrega == null) ? " " : detalhes.dataEntrega.Value.ToShortDateString(),
                descricao = detalhes.descricao,
                valor = detalhes.valor,
                produtos = produtos
            };

            return Json(obj);
        }

    }
}

ProjetoLojaDesktop/ProjetoLojaWeb/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoLojaWeb.Models;
using ProjetoLojaData.Entity;
using ProjetoLojaData.Data;

namespace ProjetoLojaWeb.Controllers
{
    //[Authorize]
    public class ProdutoController : Controller
    {
        //
        // GET: /Produto/ProdutoData
        private ProdutoData produtoModel = new ProdutoData();
        private ImagemProdutoData ipModel = new ImagemProdutoData();
        private ProdutoVigenciaData pvp = new ProdutoVigenciaData(new ProjetoLojaEntities());


        public ActionResult Index()
        {
            List<ProdutoImagem> imagensProduto = new List<ProdutoImagem>();
            foreach (var produto in produtoModel.todosProdutos())
            {
                ProdutoImagem imgProduto = new ProdutoImagem();
                imgProduto.imagem = ipModel.obterCaminhosImagem(produto.idProduto).FirstOrDefault();
                imgProduto.id = produto.idProduto;
                imagensProduto.Add(imgProduto);
            }
            ViewBag.ListaDeCaminhos = imagensProduto;
            ViewBag.ProdutoVigenciaPreco = pvp.todosProdutoVigencia();
            return View(produtoModel.todosProdutos());        
        }

        public ActionResult Details(int id)
        {
            Produto p;
            if (id == 0)
            {
                p = new Produto();
            }
            else
            {
                p = produtoModel.obterProduto(id);
            }
           
            ViewBag.Imagem = ipModel.obterCaminhosImagem(id);
            ViewBag.PrimeiraImagem = ipModel.obterCaminhosImagem(id).FirstOrDefault();
            ViewBag.ProdutoVigenciaPreco = pvp.obterProdutoVigenciaPorIdProduto(id);
            return View(p);
        }

    }
}

ProjetoLojaDesktop/ProjetoLojaWeb/Views/Shared/Produtos.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en" class="no-js">

    <head>
        <meta charset="UTF-8" />

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>PROJETO LOJA</title>


<link rel="stylesheet" type="text/css" href="../../Style/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="../../Style/css/bootstrap-responsive.css" />
<link rel="stylesheet" type="text/css" href="../../Style/css/fonts/font-awesome.css" />
<link rel="stylesheet" type="text/css" href="../../Style/css/flexslider.css" />
<!-- Comment following two lines to use LESS -->
<link rel="stylesheet" type="text/css" href="../../Style/css/color-schemes/core.css" />
<link rel="stylesheet" type="text/css" href="../../Style/css/color-schemes/turquoise.css" id="color_scheme" />





<link rel="icon" href="favicon.ico" type="image/x-icon" />
<link href="http://fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic|Shadows+Into+Light" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>


<script type="text/javascript" src="../../Style/js/jquery-ui-1.10.2.custom.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.easing-1.3.min.js"></script>
<script type="text/javascript" src="../../Style/js/bootstrap.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.isotope.min.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.flexslider.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.elevatezoom.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.sharrre-1.3.4.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.gmap3.js"></script>
<script type="text/javascript" src="../../Style/js/jquery.tweet.js"></script>
<script type="text/javascript" src="../../Style/js/imagesloaded.js"></script>
<script type="text/javascript" src="../../Style/js/la_boutique.js"></script>

<!--preview only-->
<script type="text/javascript" src="../../Style/js/jquery.cookie.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>  
      <!--Aqui começa o cabeçalho-->     
    <body>

        <div class="wrapper">

            <!-- Header -->
<div class="header">
    <div class="bottom">
        <div class="container">
            <div class="row">
                <div class="span8">							
                    <div class="logo">
                        <a href="/" title="&larr; Back home">
                            <img src="../../Style/img/layout_set_logo.png" alt="UNIPAM" />
                        </a>
                    </div>
                </div>
           </div>
        </div>
    </div>
<nav class="navigation">
    <div class="container">
        <div class="row">
            <div class="">
                <div class="hidden-phone">
                    <ul class="main-menu">
                            <li><a href="/OrdemServico">Ordens de Serviço</a></li>
                            <li><a href="/">Home</a></li>
                            <li><a href="/Produto">Produto</a></li>
                            <li><a href="/Home/About">About</a></li>
                            <li><a href="/Home/Contact">Contact</a></li>				
                    </ul>
                </div>
            </div>
            <div class="span3 visible-desktop"> </div>
        </div>
    </div>
</nav>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>


        <div class="footer">
    <div class="container">
        <div class="row">	
            <div class="span8">
				<div class="social">
                    <h6>Encontre-nos</h6>

                    <ul class="social-icons">

                        <li>
                            <a class="twitter" href="#" title="Twitter">Twitter</a>								
                        </li>

                        <li>
                            <a class="facebook" href="#" title="Facebook">Facebook</a>								
                        </li>
						<li>
                            <a class="googleplus" href="#" title="Google+">Google+</a>								
                        </li>
                        <li>
                            <a class="instagram" href="#" title="Instagram">Instagram</a>								
                        </li>

                    </ul>
                </div>
			</div>
            <div class="span4">				
                <div class="newsletter">
                    <h6>Newsletter</h6>

                    <form onsubmit="$('#newsletter_subscribe').modal('show'); return false;" enctype="multipart/form-data" action="/" method="post" />                       
                        <div class="input-append">
                            <input type="text" class="span3" name="email" />
                            <button class="btn" type="submit">Assinar</button>
                        </div>                       
                    </form>								
                    <p>Cadastre-se para receber nossas dicas.</p>
                </div>
                <hr />
            </div>
        </div>
    </div>
</div>
<!-- End id="footer" -->
            <!-- Credits bar -->
<div class="credits">
    <div class="container">
        <div class="row">
            <div class="span8">
                <p>&copy; 2014 <a href="#" title="La Boutique">ProjetoLoja</a>&middot; Todos os direitos reservados. </p>
            </div>
        </div>
    </div>
</div>
<div id="newsletter_subscribe" class="modal hide fade" tabindex="-1">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <div class="hgroup title">
            <h3>You are now subscribed to our newsletter</h3>
            <h5>All the latest deals and offers will be making their way to your inbox shortly!</h5>
        </div>
    </div>

    <div class="modal-footer">	
        <div class="pull-left">
            <button data-dismiss="modal" aria-hidden="true" class="btn btn-small">
                Close &nbsp; <i class="icon-ok"></i>
            </button>
        </div>
    </div>
</div>
<!-- End id="newsletter_subscribe" -->          
        </div>
<!-- I'm watching you -->
<script type="text/javascript">
    var sc_project = 9238432;
    var sc_invisible = 1;
    var sc_security = "e08559e3";
    var sc_https = 1;
    var sc_remove_link = 1;
    var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
    document.write("<sc" + "ript type='text/javascript' src='" +
scJsHost +
"statcounter.com/counter/counter.js'></" + "script>");
</script>
<!-- Okay I'll stop watching you -->
    </body>
</html>

ProjetoLojaDesktop/ProjetoLojaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/bootstrap-min.css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Ordens de Serviço", "Index", "OrdemServico")</li>
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Produto", "Index", "Produto")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>